// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { defineMcp } from "npm:@lovable.dev/mcp-js@0.24.0";

// src/lib/mcp/tools/get-profile.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@0.24.0";

// src/lib/mcp/data.ts
var profile = {
  name: "Akshit Pratiush",
  title: "Senior Solutions Architect",
  location: "Bengaluru, India",
  email: "apratiush@gmail.com",
  phone: "+91 97411 39265",
  github: "https://github.com/aksprat",
  linkedin: "https://www.linkedin.com/in/akshit-pratiush",
  summary: "Experienced architect designing scalable cloud solutions across AWS, Google Cloud & DigitalOcean. Passionate about cloud migrations, cost optimization & technical leadership."
};
var experience = [
  {
    company: "DigitalOcean",
    role: "Senior Solutions Architect",
    period: "Dec 2022 \u2013 Present",
    highlights: [
      "Led end-to-end cloud migration from AWS to DigitalOcean, resulting in multi-million-pound contracts.",
      "Designed scalable infrastructure for data analytics platforms with auto-scaling and managed databases.",
      "Built reusable IaC modules (Terraform, Ansible) to accelerate client onboarding.",
      "Performed architecture reviews and cost audits, improving resource utilization by up to 40%.",
      "Led POC sessions with enterprise clients involving Kubernetes, PostgreSQL, and VPC networking.",
      "Authored technical white papers and case studies for the wider technology community.",
      "Conducted technical workshops and webinars to educate clients on product features.",
      "Led generative AI POCs and demos on DigitalOcean Gradient AI Platform.",
      "Designed LLM-based architectures leveraging GPU inference, managed databases, object storage, and containerized microservices.",
      "Advised customers on GPU selection, AI workload sizing, and cost-performance trade-offs."
    ]
  },
  {
    company: "Google Operations Center",
    role: "Cloud Engineer Specialist",
    period: "Oct 2021 \u2013 Dec 2022",
    highlights: [
      "Technical trainer providing Google Cloud training to new hires and experienced staff.",
      "Led and managed a team of 10 big data support engineers.",
      "Provided expert guidance on cloud architecture best practices.",
      "Upskilled internal engineers through cloud-focused training programs."
    ]
  },
  {
    company: "T-Systems",
    role: "Cloud Consultant",
    period: "Nov 2018 \u2013 Oct 2021",
    highlights: [
      "Designed and deployed Citrix on the public cloud with PowerShell automation.",
      "Set up FSLogix profiles on Azure NetApp platform.",
      "Consistently reduced Azure services costs and improved virtual desktop performance.",
      "Oversaw environment monitoring and application performance."
    ]
  },
  {
    company: "Citrix",
    role: "Technical Lead / Solutions Engineer",
    period: "Aug 2014 \u2013 Oct 2018",
    highlights: [
      "Managed a team of around 10 people as Technical Lead.",
      "Handled escalated cases with efficiency and professionalism.",
      "Conducted technical training sessions for team members.",
      "Specialized in Provisioning Services and Machine Creation Services."
    ]
  }
];
var skills = [
  "Cloud Architecture Design",
  "Infrastructure as Code",
  "Customer Engagement",
  "Project Management",
  "Kubernetes & Containerization",
  "Cloud Migration Strategies",
  "Cost Optimization",
  "Technical Leadership & Mentoring",
  "LLMs \u2013 Inference & Deployment",
  "GPU-based Workloads (Training & Inference)"
];
var education = [
  { degree: "Master of Science \u2013 Data Science", university: "John Moores University, Liverpool", year: "2026", gpa: "6.2" },
  { degree: "B.Tech \u2013 Computer Science", university: "Biju Patnaik University of Technology", year: "2014", gpa: "7.2" }
];
var certifications = [
  "NVIDIA-Certified Associate \u2013 AI Infrastructure and Operations",
  "AWS AI/ML Practitioner",
  "Google Cloud Certified \u2013 Associate Cloud Engineer",
  "Google Cloud Certified \u2013 Cloud Digital Leader",
  "Microsoft Certified \u2013 Azure Fundamentals (AZ-900)",
  "Citrix Certified Professional \u2013 Virtualization (CCP-V)"
];
var awards = [
  { company: "DigitalOcean", items: ["Annual Golden Fin Award, 2025", "Sammy Pearl Award, Q1 2024", "Sammy Pearl Award, Q1 2023"] },
  { company: "Google Operations Center", items: ["Touchstone Award \u2013 Individual Contributor, Dec 2021"] },
  { company: "T-Systems", items: ["Above and Beyond Award Q1 2020 \u2013 Cloud Migration Project"] },
  { company: "Citrix", items: ["Kudos Award Q2 2015", "Kudos Award Q3 2015", "Performance Award Q1 2016", "Excellence Award Q2 2016", "Kudos Award Q2 2017", "Kudos Award Q1 2018"] }
];
var publications = {
  tutorials: [
    { title: "Sending App Platform Logs to DO Managed OpenSearch", url: "https://www.digitalocean.com/community/tutorials/sending-app-platform-logs-to-do-managed-opensearch" },
    { title: "Partner Connect GCP", url: "https://www.digitalocean.com/community/tutorials/partner-connect-gcp" },
    { title: "Connect VPC to Azure Using Megaport", url: "https://www.digitalocean.com/community/tutorials/connect-vpc-to-azure-using-megaport" },
    { title: "Integrate Telegram Bot with Gen AI", url: "https://www.digitalocean.com/community/tutorials/integrate-telegram-bot-gen-ai" },
    { title: "Chatbot for Ghost Website", url: "https://www.digitalocean.com/community/tutorials/chatbot-for-ghost-website" }
  ],
  videos: ["Jnnq16hr-fM", "KYY5IhhOS3Q", "AHRd4YjbH6c", "MW6B27sGeDs", "cgw6WoLcQ6w", "xSEis5gTK0E"].map((id) => ({
    id,
    url: `https://www.youtube.com/watch?v=${id}`
  }))
};

// src/lib/mcp/tools/get-profile.ts
var get_profile_default = defineTool({
  name: "get_profile",
  title: "Get profile",
  description: "Return Akshit Pratiush's basic profile: name, title, location, and contact details.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: () => ({
    content: [{ type: "text", text: JSON.stringify(profile, null, 2) }],
    structuredContent: { profile }
  })
});

// src/lib/mcp/tools/get-experience.ts
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.24.0";
var get_experience_default = defineTool2({
  name: "get_experience",
  title: "Get work experience",
  description: "Return Akshit Pratiush's professional experience history (companies, roles, periods, highlights).",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: () => ({
    content: [{ type: "text", text: JSON.stringify(experience, null, 2) }],
    structuredContent: { experience }
  })
});

// src/lib/mcp/tools/get-skills.ts
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.24.0";
var get_skills_default = defineTool3({
  name: "get_skills",
  title: "Get core skills",
  description: "Return Akshit Pratiush's core technical skills.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: () => ({
    content: [{ type: "text", text: skills.join("\n") }],
    structuredContent: { skills }
  })
});

// src/lib/mcp/tools/get-education.ts
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@0.24.0";
var get_education_default = defineTool4({
  name: "get_education",
  title: "Get education",
  description: "Return Akshit Pratiush's academic education history.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: () => ({
    content: [{ type: "text", text: JSON.stringify(education, null, 2) }],
    structuredContent: { education }
  })
});

// src/lib/mcp/tools/get-certifications.ts
import { defineTool as defineTool5 } from "npm:@lovable.dev/mcp-js@0.24.0";
var get_certifications_default = defineTool5({
  name: "get_certifications",
  title: "Get certifications",
  description: "Return Akshit Pratiush's professional certifications.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: () => ({
    content: [{ type: "text", text: certifications.join("\n") }],
    structuredContent: { certifications }
  })
});

// src/lib/mcp/tools/get-awards.ts
import { defineTool as defineTool6 } from "npm:@lovable.dev/mcp-js@0.24.0";
var get_awards_default = defineTool6({
  name: "get_awards",
  title: "Get awards",
  description: "Return awards and recognitions received by Akshit Pratiush across employers.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: () => ({
    content: [{ type: "text", text: JSON.stringify(awards, null, 2) }],
    structuredContent: { awards }
  })
});

// src/lib/mcp/tools/get-publications.ts
import { defineTool as defineTool7 } from "npm:@lovable.dev/mcp-js@0.24.0";
var get_publications_default = defineTool7({
  name: "get_publications",
  title: "Get publications and videos",
  description: "Return Akshit Pratiush's public technical tutorials and video contributions.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: () => ({
    content: [{ type: "text", text: JSON.stringify(publications, null, 2) }],
    structuredContent: publications
  })
});

// src/lib/mcp/index.ts
var mcp_default = defineMcp({
  name: "akshit-pratiush-portfolio",
  title: "Akshit Pratiush Portfolio",
  version: "0.1.0",
  instructions: "Public MCP server exposing Akshit Pratiush's portfolio: profile, work experience, skills, education, certifications, awards, and publications. All tools are read-only.",
  tools: [
    get_profile_default,
    get_experience_default,
    get_skills_default,
    get_education_default,
    get_certifications_default,
    get_awards_default,
    get_publications_default
  ]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.24.0/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
