// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { defineMcp } from "npm:@lovable.dev/mcp-js@0.24.0";

// src/lib/mcp/tools/get-profile.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@0.24.0";

// src/lib/mcp/data.ts
var profile = {
  name: "Akshit Pratiush",
  title: "Senior Solutions Architect II",
  location: "Bengaluru, India",
  email: "apratiush@gmail.com",
  phone: "+91 97411 39265",
  github: "https://github.com/aprat2406",
  linkedin: "https://www.linkedin.com/in/akshit-pratiush",
  summary: "Senior Solutions Architect with 10+ years designing and scaling cloud-native and Generative AI platforms. Expert in LLM-based architectures, GPU-backed inference workloads, Kubernetes and managed AI services (including DigitalOcean Gradient AI). Strong background in cloud migrations, cost optimisation, enterprise pre-sales and customer POCs delivering multi-million contracts and 30% efficiency gains."
};
var experience = [
  {
    company: "DigitalOcean",
    role: "Senior Solutions Architect II",
    period: "Dec 2022 \u2013 Present",
    highlights: [
      "Designed LLM-based application architectures leveraging GPU-backed inference, managed databases, object storage, and containerized microservices.",
      "Advised customers on GPU selection, AI workload sizing, and cost-performance trade-offs for inference and light model training.",
      "Developed evals for GenAI prototypes, ensuring reliability and alignment in enterprise settings.",
      "Led end-to-end cloud migration of a complex production workload from AWS to DigitalOcean, resulting in multi-million pound contracts.",
      "Designed scalable cloud infrastructure for a data analytics platform with auto-scaling and optimized managed databases.",
      "Led multiple generative AI POCs and customer demos on the DigitalOcean Gradient AI Platform.",
      "Performed architecture reviews and cost audits, improving resource utilization by up to 40%.",
      "Engaged in pre-sales activities, presenting technical proposals and demonstrating solution value to prospective clients.",
      "Collaborated with product managers to define technical requirements and plan the product roadmap.",
      "Conducted technical workshops and webinars to educate clients on product features."
    ]
  },
  {
    company: "Google Operations Center",
    role: "Cloud Engineer Specialist",
    period: "Oct 2021 \u2013 Dec 2022",
    highlights: [
      "Technical trainer providing Google Cloud training to new hires and experienced staff.",
      "Led and managed a team of 10 data support engineers.",
      "Provided expert guidance on cloud architecture best practices.",
      "Upskilled internal engineers through cloud-focused training programs."
    ]
  },
  {
    company: "T-Systems",
    role: "Cloud Consultant",
    period: "Nov 2018 \u2013 Oct 2021",
    highlights: [
      "Designed and deployed Citrix on the public cloud with PowerShell automation.",
      "Set up FSLogix profiles on Azure NetApp platform.",
      "Consistently reduced Azure services costs and improved virtual desktop performance.",
      "Oversaw environment monitoring and application performance as Login Enterprise liaison."
    ]
  },
  {
    company: "Citrix",
    role: "Technical Lead / Technical Support Engineer",
    period: "Aug 2014 \u2013 Oct 2018",
    highlights: [
      "Managed a team of around 10 people as Technical Lead.",
      "Handled escalated cases with efficiency and professionalism.",
      "Conducted technical training sessions for team members.",
      "Resolved HDX, graphics and OS services technical challenges efficiently."
    ]
  }
];
var skills = [
  "Cloud Architecture Design",
  "GPU-based Workloads (Training & Inference)",
  "Infrastructure as Code",
  "Kubernetes & Containerization",
  "Cost Optimization for Cloud Services",
  "LLMs \u2013 Inference & Deployment",
  "Customer Engagement",
  "Project Management",
  "Cloud Migration Strategies",
  "Technical Leadership & Mentoring"
];
var education = [
  { degree: "Master of Science \u2013 Data Science", university: "John Moores University, Liverpool", year: "2024 \u2013 2026", gpa: "6.2" },
  { degree: "B.Sc. \u2013 Computer Science", university: "Biju Patnaik University of Technology, Bhubaneswar", year: "2010 \u2013 2014", gpa: "7.2" }
];
var certifications = [
  "Claude Certified Architect \u2013 Foundations",
  "NVIDIA-Certified Associate \u2013 AI Infrastructure and Operations",
  "AWS AI/ML Practitioner",
  "Google Cloud Certified \u2013 Associate Cloud Engineer",
  "Google Cloud Certified \u2013 Cloud Digital Leader",
  "Microsoft Certified \u2013 Azure Fundamentals (AZ-900)",
  "Citrix Certified Professional \u2013 Virtualization (CCP-V)"
];
var awards = [
  { company: "DigitalOcean", items: ["Golden Fin Award, Dec 2025", "Sammy Pearl Award, Jun 2024", "Sammy Pearl Award, Mar 2023"] },
  { company: "Google Operations Center", items: ["Touchstone Award \u2013 Individual Contributor, May 2022"] },
  { company: "T-Systems", items: ["Above and Beyond Award, Aug 2019"] },
  { company: "Citrix", items: ["Kudos Award", "Performance Award", "Excellence Award"] }
];
var publications = {
  tutorials: [
    { title: "DigitalOcean Inference Mode Comparison for Your Use Case", url: "https://www.digitalocean.com/community/tutorials" },
    { title: "Upload a File to DigitalOcean Spaces Using AWS C++ SDK", url: "https://www.digitalocean.com/community/tutorials" },
    { title: "How to Use AWS Java SDK with DigitalOcean Spaces", url: "https://www.digitalocean.com/community/tutorials" },
    { title: "Connecting DigitalOcean VPC to Microsoft Azure via Megaport", url: "https://www.digitalocean.com/community/tutorials/connect-vpc-to-azure-using-megaport" },
    { title: "Sending App Platform Logs to DO Managed OpenSearch", url: "https://www.digitalocean.com/community/tutorials/sending-app-platform-logs-to-do-managed-opensearch" },
    { title: "Partner Connect GCP", url: "https://www.digitalocean.com/community/tutorials/partner-connect-gcp" },
    { title: "Integrate Telegram Bot with Gen AI", url: "https://www.digitalocean.com/community/tutorials/integrate-telegram-bot-gen-ai" },
    { title: "Chatbot for Ghost Website", url: "https://www.digitalocean.com/community/tutorials/chatbot-for-ghost-website" },
    { title: "Visualise Spaces Access Logs", url: "https://www.digitalocean.com/community/tutorials" }
  ],
  videos: ["Jnnq16hr-fM", "KYY5IhhOS3Q", "AHRd4YjbH6c", "MW6B27sGeDs", "cgw6WoLcQ6w", "xSEis5gTK0E"].map((id) => ({
    id,
    url: `https://www.youtube.com/watch?v=${id}`
  })),
  videoStats: "3,000+ views across all videos"
};

// src/lib/mcp/tools/get-profile.ts
var get_profile_default = defineTool({
  name: "get_profile",
  title: "Get profile",
  description: "Return Akshit Pratiush's basic profile: name, title, location, and contact details.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: () => ({
    content: [{ type: "text", text: JSON.stringify(profile, null, 2) }],
    structuredContent: { profile }
  })
});

// src/lib/mcp/tools/get-experience.ts
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.24.0";
var get_experience_default = defineTool2({
  name: "get_experience",
  title: "Get work experience",
  description: "Return Akshit Pratiush's professional experience history (companies, roles, periods, highlights).",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: () => ({
    content: [{ type: "text", text: JSON.stringify(experience, null, 2) }],
    structuredContent: { experience }
  })
});

// src/lib/mcp/tools/get-skills.ts
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.24.0";
var get_skills_default = defineTool3({
  name: "get_skills",
  title: "Get core skills",
  description: "Return Akshit Pratiush's core technical skills.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: () => ({
    content: [{ type: "text", text: skills.join("\n") }],
    structuredContent: { skills }
  })
});

// src/lib/mcp/tools/get-education.ts
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@0.24.0";
var get_education_default = defineTool4({
  name: "get_education",
  title: "Get education",
  description: "Return Akshit Pratiush's academic education history.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: () => ({
    content: [{ type: "text", text: JSON.stringify(education, null, 2) }],
    structuredContent: { education }
  })
});

// src/lib/mcp/tools/get-certifications.ts
import { defineTool as defineTool5 } from "npm:@lovable.dev/mcp-js@0.24.0";
var get_certifications_default = defineTool5({
  name: "get_certifications",
  title: "Get certifications",
  description: "Return Akshit Pratiush's professional certifications.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: () => ({
    content: [{ type: "text", text: certifications.join("\n") }],
    structuredContent: { certifications }
  })
});

// src/lib/mcp/tools/get-awards.ts
import { defineTool as defineTool6 } from "npm:@lovable.dev/mcp-js@0.24.0";
var get_awards_default = defineTool6({
  name: "get_awards",
  title: "Get awards",
  description: "Return awards and recognitions received by Akshit Pratiush across employers.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: () => ({
    content: [{ type: "text", text: JSON.stringify(awards, null, 2) }],
    structuredContent: { awards }
  })
});

// src/lib/mcp/tools/get-publications.ts
import { defineTool as defineTool7 } from "npm:@lovable.dev/mcp-js@0.24.0";
var get_publications_default = defineTool7({
  name: "get_publications",
  title: "Get publications and videos",
  description: "Return Akshit Pratiush's public technical tutorials and video contributions.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: () => ({
    content: [{ type: "text", text: JSON.stringify(publications, null, 2) }],
    structuredContent: publications
  })
});

// src/lib/mcp/index.ts
var mcp_default = defineMcp({
  name: "akshit-pratiush-portfolio",
  title: "Akshit Pratiush Portfolio",
  version: "0.1.0",
  instructions: "Public MCP server exposing Akshit Pratiush's portfolio: profile, work experience, skills, education, certifications, awards, and publications. All tools are read-only.",
  tools: [
    get_profile_default,
    get_experience_default,
    get_skills_default,
    get_education_default,
    get_certifications_default,
    get_awards_default,
    get_publications_default
  ]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.24.0/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
